In [6]:
#write a python code to check the version of numby
import numpy as np
print(np.__version__)

2.1.0


In [10]:
#write a python program to test if any of the element of the give array are non zero
import numpy as np
x=np.array ([1,0,0,0,0])
print(np.any(x))
x=np.array([0,0,0,0,0])
print(np.any(x))

True
False


In [12]:
#write a python program to test given array element wise for finiteness 
import numpy as np
x=np.array([1,0,np.nan,np.inf])
print (x)
print("test a given element wise for finiteness:")
print (np.isfinite(x))

[ 1.  0. nan inf]
test a given element wise for finiteness:
[ True  True False False]


In [17]:
#write a python program to test elementwise positive or negative infinity 
import numpy as np
gray=np.array([1,-2,np.inf,-np.inf,0,3.5])
result_pos_inf=np.isposinf(gray)
result_neg_inf=np.isneginf(gray)
print(result_pos_inf)
print(result_neg_inf)


[False False  True False False False]
[False False False  True False False]


In [22]:
#write a python program to create an array of integers from 30 to 70
import numpy as np
array=np.arange(30,71)
print(array)


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [23]:
import numpy as np
array=np.arange(30,71,2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [25]:
#write a python indentity matrix
import numpy as np 
arr_2d=np.identity (3)
print(arr_2d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
#write a python program to create a 5x5 xero matrix with element on the main diagonal equal to 1,2,3,4,5
import numpy as np
x=np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [30]:
#write a pyhton product to generate product of two arrays
import numpy as np
x=[[1,0],[1,1]]
y=[[3,1],[2,2]]
print (np.dot (x,y))
print (np.matmul (x,y))

[[3 1]
 [5 3]]
[[3 1]
 [5 3]]


In [34]:
#addition & subtraction
import numpy as np
x1=np.array ([10,11,12,13,14,15])
x2=np.array([21,22,23,24,25,26])
add=np.add(x1,x2)
print(add)

[31 33 35 37 39 41]


In [35]:
#write a python program to find the mean of one D array
import numpy as np
x1=np.array([10,20,30,40,50])
me=np.mean(x1)
print(me)

30.0


In [40]:
import numpy as np
x=np.array([[10,30],[20,60]])
print("original array")
print (x)
print ("mean of each coloumn")
print (x.mean(axis=0))
print("mean of each row")
print(x.mean(axis=1))

original array
[[10 30]
 [20 60]]
mean of each coloumn
[15. 45.]
mean of each row
[20. 40.]


In [43]:
#write a python program to create 1D array in range o to 9
import numpy as np
x=np.array([0,1,2,3,4,5,6,7,8,9])
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
#write a python program to convert 1D array to 2d array
import numpy as np
x=np.array([0,1,2,3,4,5,6,7,8,9,10,12])
y=x.reshape(3,4)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 12]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 12]]
