In [3]:
#To Check version of numpy 
import numpy as np 
print(np.__version__)

1.26.4


In [5]:
#To Find any non-zero elements in an array 
import numpy as np 
x=np.array([1,0,0,0]) 
print(np.any(x)) 
y=np.array([0,0,0,0]) 
print(np.any(y))

True
False


In [7]:
#To Find Finiteness of an array 
import numpy as np 
x=np.array([1,8,np.nan, np.inf]) 
print(x) 
print("Test the finiteness of elements of an array:") 
print(np.isfinite(x))

[ 1.  8. nan inf]
Test the finiteness of elements of an array:
[ True  True False False]


In [17]:
#To Test element-wise positive or negative infinity 
import numpy as np 
x=np.array([1,-2, np.inf,-np.inf, 0,3.5]) 
result_posinf=np.isposinf(x) 
result_neginf=np.isneginf(x) 
print(result_posinf) 
print(result_neginf)

[False False  True False False False]
[False False False  True False False]


In [21]:
#To print an array in a range

import numpy as np

arr=np.arange(30,71)

print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [23]:
#To print an array of even numbers in a range

import numpy as np

arr=np.arange(30,71,2)

print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [25]:
#To print a 3x3 identity matrix 
import numpy as np 
arr=np.identity(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#To create a 5x5 diagonal matrix

import numpy as np

arr=np.diag([1,2,3,4,5])

print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [29]:
#To generate a matrix prroducts of two arrays 
import numpy as np 
x=np.array([[1,0], [1,1]]) 
y=np.array([[3,1],[2,2]]) 
print("Matrix Products") 
print(np.dot(x,y)) 
print("To cross-check") 
print(np.matmul(x,y)) 
print("Matrix addition") 
print(np.add(x,y)) 
print("Matrix Subtraction") 
print(np.subtract(x,y))

Matrix Products
[[3 1]
 [5 3]]
To cross-check
[[3 1]
 [5 3]]
Matrix addition
[[4 1]
 [3 3]]
Matrix Subtraction
[[-2 -1]
 [-1 -1]]


In [31]:
#To find mean of an array 
import numpy as np 
arr=np.array([10,20,30,40,50]) 
print(np.mean(arr))

30.0


In [33]:
#To find mean of axis of an array

import numpy as np 
arr=np.array([[10,30], [20,60]]) 
print(arr) 
print("Mean of Each Column") 
print(arr.mean(axis=0)) 
print("Mean of Each Rows")

print(arr.mean(axis=1))

[[10 30]
 [20 60]]
Mean of Each Column
[15. 45.]
Mean of Each Rows
[20. 40.]


In [37]:
#To create an array in a range 
import numpy as np

arr=np.arange(0,10) 
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
#To convert 10 array to 20 array import numpy as np

arr=np.array([10,20,30,40,50,60]) arr_2D=arr.reshape(2,3)

arr_3D=arr.reshape(3,1,2)

print("Original 10 array:")

print(arr)

print("20 aray thus created:")

print(arr_2D)

print("30 array created:")

print(arr 3D)

SyntaxError: invalid decimal literal (1820174147.py, line 17)