In [1]:
#write a python code to check the version of numpy
import numpy as np
print(np.__version__)

1.26.4


In [3]:
#program to test if any of the elements of a given array are non zero
import numpy as np
x=np.array([1,0,0,0])
print(np.any(x))
x=np.array([0,0,0,0])
print(np.any(x))

True
False


In [5]:
#program to test a given array element wise for finitness
import numpy as np
x=np.array([1,0,np.nan,np.inf])
print(x)
print("test a given element wise for finiteness:")
print(np.isfinite(x))

[ 1.  0. nan inf]
test a given element wise for finiteness:
[ True  True False False]


In [7]:
#program to test element wise positive or negative infinity
import numpy as np
array=np.array([1,-2,np.inf,-np.inf,0,3.5])
result_pos_inf=np.isposinf(array)
result_neg_inf=np.isneginf(array)
print(result_pos_inf)
print(result_neg_inf)


[False False  True False False False]
[False False False  True False False]


In [9]:
#program to create an array of integers from 30 to 70
import numpy as np
array=np.arange(30,71,2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [11]:
#program to print array in range
import numpy as np
array=np.arange(30,71)
print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [13]:
#to create 3*3 identity matrix
import numpy as np
arr_2D=np.identity(3)
print(arr_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#to create a 5*5 zero matrix with element on the main diagonal equal to 1,2,3,4,5
import numpy as np
x=np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [17]:
#program to generate a matrix product of 2 arrays
import numpy as np
x=[[1,0],[1,1]]
y=[[3,1],[2,2]]
print (np.dot(x,y))
print("To cross check")
print(np.matmul(x,y))

[[3 1]
 [5 3]]
To cross check
[[3 1]
 [5 3]]


In [19]:
#program to generate a matrix product of 2 arrays
import numpy as np
x=[[1,0],[1,1]]
y=[[3,1],[2,2]]
print("Addition of matrix")
print(np.add(x,y))
print("Subtraction of matrix")
print(np.subtract(x,y))

Addition of matrix
[[4 1]
 [3 3]]
Subtraction of matrix
[[-2 -1]
 [-1 -1]]


In [21]:
#w.p.p to find mean of 1D array
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.mean(arr))

30.0


In [23]:
#to find mean of axis an array
import numpy as np
arr=np.array([[10,30],[20,60]])
print(arr)
print("mean of each column")
print(arr.mean(axis=0))
print("mean of each row")
print(arr.mean(axis=1))

[[10 30]
 [20 60]]
mean of each column
[15. 45.]
mean of each row
[20. 40.]


In [25]:
#to convert 1D to 2D array with 2 rows
import numpy as np
arr=np.array([10,20,30,40,50,60])
arr_2D=arr.reshape(2,3)
print(arr_2D)

[[10 20 30]
 [40 50 60]]


In [27]:
#create 1D array in range 0 to 9
import numpy as np
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
